// <auto-generated />
namespace Base_de_Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Secundaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Secundaria));
        
        string IMigrationMetadata.Id
        {
            get { return "202104220309007_Secundaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
